version: "3"

services:
  equipment-nginx:
      build:
        context: ./config/nginx
        args:
          - PROJECT_HOST=${PROJECT_HOST}
          - PROJECT_NAME=${PROJECT_NAME}
      image: ${PROJECT_NAME}-nginx
      volumes:
          - ./../website:/var/www/vhosts/website
      container_name: ${PROJECT_NAME}-nginx
      expose:
         - 80
      ports:
        - ${PROJECT_PORT}:80
      restart: on-failure:10

  equipment-php:
      build: ./config/php
      image: ${PROJECT_NAME}-v2-php:7.3-fpm
      volumes:
          - ./../website:/var/www/vhosts/website
          - ./../website/vendor:/var/www/vhosts/website/vendor:cached
      container_name: ${PROJECT_NAME}-php
      depends_on:
        - ${PROJECT_NAME}-nginx
      environment:
          XDEBUG_CONFIG: remote_host=${NGINX_IP}
      working_dir: /var/www/vhosts/website/
      restart: on-failure:10

  equipment-mariadb:
      image: mariadb:latest
      container_name: ${PROJECT_NAME}-mariadb
      environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      expose:
        - 3306
      ports:
        - "${MYSQL_PORT}:3306"
      depends_on:
        - ${PROJECT_NAME}-php
      volumes:
        - ./data-mysql:/var/lib/mysql

networks:
  default:
    external:
      name: equipment
